disableStartupPopups: true
gui:
  nerdFontsVersion: "3"
  filterMode: "fuzzy"
  showRandomTip: false
  showCommandLog: false
git:
  overrideGpg: true
  parseEmoji: true
os:
  editPreset: nvim
keybinding:
  commits:
    markCommitAsBaseForRebase: "<c-b>"
customCommands:
  - key: <c-P>
    command: get_pr_worktrees "{{ .Form.PrNumber }}"
    context: localBranches
    loadingText: Checkout out PR {{ .Form.PrNumber }}
    prompts:
      - type: menuFromCommand
        title: "Pull Request"
        key: PrNumber
        command: gh pr list
        filter: '^(?P<pr>\d+)\t(?P<title>[^\t]+)\t(?P<branch>[^\t]+)\t.+$'
        valueFormat: "{{ .pr }}"
        labelFormat: "{{ .pr | bold | cyan }} {{ .title }} {{ .branch }}"
    description: Check out PR branch
  - key: <c-b>
    command: tig blame -- "{{ .SelectedFile.Name }}"
    context: files
    description: Blame file at tree
    output: terminal
  - key: <c-b>
    command: tig blame "{{ .SelectedSubCommit.Sha }}" -- "{{ .SelectedCommitFile.Name }}"
    context: commitFiles
    description: Blame file at revision
    output: terminal
  - key: <c-B>
    command: tig blame -- "{{ .SelectedCommitFile.Name }}"
    context: commitFiles
    description: Blame file at tree
    output: terminal
  - key: t
    command: tig show {{ .SelectedSubCommit.Sha }}
    context: subCommits
    description: tig commit (`t` again to browse files at revision)
    output: terminal
  - key: t
    command: tig show "{{ .SelectedLocalBranch.Name }}"
    context: localBranches
    description: tig branch (`t` again to browse files at revision)
    output: terminal
  - key: t
    command: tig show "{{ .SelectedRemoteBranch.RemoteName }}/{{ .SelectedRemoteBranch.Name }}"
    context: remoteBranches
    description: tig branch (`t` again to browse files at revision)
    output: terminal
  - key: t
    command: tig {{ .SelectedSubCommit.Sha }} -- "{{ .SelectedCommitFile.Name }}"
    context: commitFiles
    description: tig file (history of commits affecting file)
    output: terminal
  - key: t
    command: tig -- "{{ .SelectedFile.Name }}"
    context: files
    description: tig file (history of commits affecting file)
    output: terminal
