require("core.options")

local plugin_modules = {
  "plugins.ai",
  "plugins.bash",
  "plugins.bufferline",
  "plugins.chezmoi",
  "plugins.colorscheme",
  "plugins.completion",
  "plugins.core",
  "plugins.dap",
  "plugins.diff",
  "plugins.docker",
  "plugins.eslint",
  "plugins.fish",
  "plugins.formatting",
  "plugins.fzf",
  "plugins.git",
  "plugins.github",
  "plugins.go",
  "plugins.gx",
  "plugins.helm",
  "plugins.highlight",
  "plugins.hlargs",
  "plugins.html-css",
  "plugins.inc-rename",
  "plugins.jinja",
  "plugins.json",
  "plugins.jsonl",
  "plugins.kdl",
  "plugins.lazydev",
  "plugins.leap",
  "plugins.lint",
  "plugins.live-command",
  "plugins.lsp",
  "plugins.lua",
  "plugins.lualine",
  "plugins.markdown",
  "plugins.marks",
  "plugins.multi-cursors",
  "plugins.neo-tree",
  "plugins.numb",
  "plugins.osv",
  "plugins.outline",
  "plugins.python",
  "plugins.rust",
  "plugins.search-and-replace",
  "plugins.session",
  "plugins.snacks",
  "plugins.strudel",
  "plugins.telescope",
  "plugins.tpope",
  "plugins.treesitter",
  "plugins.typescript-tools",
  "plugins.undo",
  "plugins.which-key",
  "plugins.xml",
  "plugins.yaml",
}

local local_modules = {
  "plugins_local.copy-to-qf",
  "plugins_local.freeze",
  "plugins_local.lsp-progress",
  "plugins_local.owner-code-search",
  "plugins_local.qf",
  "plugins_local.run-jest-in-split",
  "plugins_local.send-to-tmux-right-pane",
  "plugins_local.show-file-owner",
  "plugins_local.summarize-commit",
  "plugins_local.switch-src-test",
  "plugins_local.toggle-win-width",
  "plugins_local.ts-move-exports",
  "plugins_local.unwrap-md",
  "plugins_local.winbar",
}

local all_modules = {}
vim.list_extend(all_modules, plugin_modules)
vim.list_extend(all_modules, local_modules)

require("core.plugins").setup(all_modules)

require("core.autocmds")
require("core.keymaps")
