set-option -sa terminal-overrides ",xterm*:Tc"
set -g mouse on
set -g default-terminal "alacritty"
set-option -sa terminal-features ',alacritty:RGB'
set-option -ga terminal-features ",alacritty:usstyle"
set-option -ga terminal-overrides ',alacritty:Tc'
set -g renumber-windows on

# set vi-mode
set-window-option -g mode-keys vi

unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# No confirm to kill
bind-key & kill-window
bind-key x kill-pane

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Shift Alt vim keys to switch windows
bind -n M-H previous-window
bind -n M-L next-window

# Shift F to toggle max-pane
unbind-key z 
unbind-key f
bind-key f resize-pane -Z

# Reload config
bind r source-file ~/.config/tmux/tmux.conf

# History and renaming
set -g history-limit 10000
set -g allow-rename off

# keybindings
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

set -g @plugin '27medkamal/tmux-session-wizard'
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'fcsonline/tmux-thumbs'
set -g @plugin 'jaclu/tmux-menus'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-copycat'
set -g @plugin 'tmux-plugins/tmux-open'
set -g @plugin 'tmux-plugins/tmux-pain-control'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-sessionist'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tpm'

set -g @catppuccin_flavour 'frappe'

# Thumbs
set -g @thumbs-key 'y'
set -g @thumbs-command 'echo -n {} | pbcopy'
set -g @thumbs-alphabet 'qwerty-left-hand'
set -g @thumbs-reverse enabled
set -g @thumbs-contrast 1
set -g @thumbs-upcase-command 'echo -n {} | pbcopy'

# Continuum
set -g @continuum-restore 'on'
set -g @continuum-boot 'on'
set -g @continuum-boot-options 'wezterm,fullscreen'
set -g status-right 'Continuum status: #{continuum_status}'
set -g @continuum-save-interval '1'

# Menus
set -g @menus_trigger 'e'
set -g @menus_location_x 'C'
set -g @menus_location_y 'C'

# Open
set -g @open 'x'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/plugins/tpm/tpm'

# tpm overrides

# Override tmux-pain-control because >< don't work
unbind-key >
unbind-key <
unbind-key C-h
unbind-key C-l

bind-key s switch-client -T k18
# <prefix>sh to swap left
bind-key -T k18 h swap-pane -d -t -1
# <prefix>sl to swap right
bind-key -T k18 l swap-pane -d -t +1

