// Code generated by scripts/model_mirrors.py; DO NOT EDIT.

package state

const (
	generatedModelMirrorSchemaVersion = "1.0.0"
	generatedModelMirrorSHA256        = "be4c4159f8ffd704983a6794d685373cfa44cfdbd57f2233eb5aeb5287eea73e"
)

var generatedRecommendedModels = map[string][]string{
	"cursor": {
		"composer-2.5",
		"composer-2.5-fast",
		"claude-opus-4-8-xhigh",
		"claude-opus-4-8-xhigh-fast",
		"claude-opus-4-8-thinking-xhigh",
		"claude-opus-4-8-thinking-xhigh-fast",
		"gpt-5.5-high",
		"gpt-5.5-high-fast",
		"gpt-5.5-none",
		"gpt-5.5-none-fast",
		"gpt-5.5-low",
		"gpt-5.5-low-fast",
		"gpt-5.5-medium",
		"gpt-5.5-medium-fast",
		"gpt-5.5-extra-high",
		"gpt-5.5-extra-high-fast",
		"gpt-5.3-codex-low",
		"gpt-5.3-codex-low-fast",
		"gpt-5.3-codex",
		"gpt-5.3-codex-fast",
		"gpt-5.3-codex-high",
		"gpt-5.3-codex-high-fast",
		"gpt-5.3-codex-xhigh",
		"gpt-5.3-codex-xhigh-fast",
		"gemini-3.1-pro",
		"gemini-3.5-flash",
	},
	"pi": {
		"llm-gateway/gemini-3.1-pro-preview",
		"llm-gateway/gemini-3.1-pro-preview-customtools",
		"llm-gateway/claude-haiku-4-5",
		"llm-gateway/Kimi-K2.6",
		"llm-gateway/gpt-5.6-luna",
		"llm-gateway/gpt-5.6-terra",
		"llm-gateway/gpt-5.6-sol",
		"llm-gateway/gpt-5.5",
		"llm-gateway/claude-opus-4-8",
		"llm-gateway/claude-sonnet-5",
		"llm-gateway/claude-fable-5",
		"llm-gateway/claude-opus-4-7",
		"llm-gateway/gemini-3.5-flash",
		"openrouter/anthropic/claude-opus-4.7-thinking",
		"openrouter/anthropic/claude-opus-4.7",
		"openrouter/openai/gpt-5.5",
		"openrouter/openai/gpt-5.3-codex",
		"openrouter/google/gemini-3.1-pro-preview-customtools",
		"openrouter/google/gemini-3.5-flash",
	},
}

var generatedRalphRoleDefaults = map[string]RoleSpec{
	"planner":     {Harness: "cursor", Model: "claude-opus-4-8-thinking-xhigh"},
	"executor":    {Harness: "cursor", Model: "composer-2.5"},
	"reviewer":    {Harness: "cursor", Model: "claude-opus-4-8-thinking-xhigh"},
	"re_reviewer": {Harness: "cursor", Model: "gpt-5.5-extra-high"},
}
