#!/bin/bash

set -x
set -euo pipefail

# ==============================================
# .osx.user
# adapted from https://github.com/hjuutilainen/dotfiles/tree/45cb437288f7b0633a2c59ea7bcee184f11b028a/bin#
# ==============================================

# Enable automatic update check and download
defaults write /Library/Preferences/com.apple.SoftwareUpdate AutomaticCheckEnabled -bool true
defaults write /Library/Preferences/com.apple.SoftwareUpdate AutomaticDownload -bool true

# Enable app update installs
defaults write /Library/Preferences/com.apple.commerce AutoUpdate -bool true

# Enable system data files and security update installs
defaults write /Library/Preferences/com.apple.SoftwareUpdate ConfigDataInstall -bool true
defaults write /Library/Preferences/com.apple.SoftwareUpdate CriticalUpdateInstall -bool true

# Enable OS X update installs
defaults write /Library/Preferences/com.apple.commerce AutoUpdateRestartRequired -bool true

#
# Files and folders
#

# Show the ~/Library directory
chflags nohidden "${HOME}/Library"

#
# NSGlobalDomain settings
#
echo "Setting NSGlobalDomain preferences"

# Interface style: Light
# defaults delete -g AppleInterfaceStyle >/dev/null 2>&1 || true
# defaults delete -g AppleInterfaceStyleSwitchesAutomatically >/dev/null 2>&1 || true

# Interface style: Dark
defaults write -g AppleInterfaceStyle -string "Dark"
defaults delete -g AppleInterfaceStyleSwitchesAutomatically >/dev/null 2>&1 || true

# Interface style: Auto
# defaults delete -g AppleInterfaceStyle > /dev/null 2>&1 || true
# defaults write -g AppleInterfaceStyleSwitchesAutomatically -bool true

# Don't automatically hide and show the menu bar
defaults write -g _HIHideMenuBar -bool false

# Don't allow wallpaper tinting in windows
defaults write -g AppleReduceDesktopTinting -bool true

# Language and Region (locale)
defaults write -g AppleLanguages -array "en-US"
defaults write -g AppleLocale -string "en_US"
defaults write -g AppleMeasurementUnits -string "Centimeters"
defaults write -g AppleMetricUnits -bool true
defaults write -g AppleTemperatureUnit -string "Celsius"

# First day of week, 1 = Sunday, 2 = Monday, etc.
defaults write -g AppleFirstWeekday -dict gregorian -int 2

# Default date format
defaults delete -g AppleICUDateFormatStrings >/dev/null 2>&1 || true

# Custom date format
# defaults write -g AppleICUDateFormatStrings -dict 1 "y-MM-dd"

# 24-Hour Time
defaults write -g AppleICUForce12HourTime -bool false

# Live Text
defaults write -g AppleLiveTextEnabled -bool true

# Turn off text smoothing for font sizes
defaults write -g AppleAntiAliasingThreshold -int 4

# Double-click a window's title bar to zoom
defaults write -g AppleMiniaturizeOnDoubleClick -bool true

# Use smooth scrolling
defaults write -g AppleScrollAnimationEnabled -bool true

# Enable key repeat
defaults write -g ApplePressAndHoldEnabled -bool false

# Set keyboard repeat rate
defaults write -g KeyRepeat -int 1
defaults write -g InitialKeyRepeat -int 2

# Don't restore windows when quitting or re-opening apps
defaults write -g NSQuitAlwaysKeepsWindows -bool false

# Don't reopen windows when logging back in
defaults write com.apple.loginwindow LoginwindowLaunchesRelaunchApps -bool false

# Disable window animations
# https://github.molgen.mpg.de/pages/bs/macOSnotes/mac/mac_system_anim.html
defaults write -g NSAutomaticWindowAnimationsEnabled -bool false

# Set window resize time
defaults write -g NSWindowResizeTime -float 0.001

# Enable text completion
defaults write -g NSAutomaticTextCompletionEnabled -bool true

# Disable automatic spelling correction
defaults write -g NSAutomaticSpellingCorrectionEnabled -bool false
defaults write -g WebAutomaticSpellingCorrectionEnabled -bool false

# Automatically identify language for spelling correction
defaults write -g NSSpellCheckerAutomaticallyIdentifiesLanguages -bool true

# Disable capitalize words automatically
defaults write -g NSAutomaticCapitalizationEnabled -bool false

# Disable double-space to period
defaults write -g NSAutomaticPeriodSubstitutionEnabled -bool false

# Disable smart quotes and dashes
defaults write -g NSAutomaticDashSubstitutionEnabled -bool false
defaults write -g NSAutomaticQuoteSubstitutionEnabled -bool false

# Sidebar icon size: Small
defaults write -g NSTableViewDefaultSizeMode -int 1

# Show scroll bars: Always, Automatic, WhenScrolling
defaults write -g AppleShowScrollBars Automatic

# Click in the scroll bar to: Jump to the next page
defaults write -g AppleScrollerPagingBehavior -int 0

# Ask to keep changes when closing documents
defaults write -g NSCloseAlwaysConfirmsChanges -bool true

# Don't try to save to iCloud by default
defaults write -g NSDocumentSaveNewDocumentsToCloud -bool false

# Disable App Nap for all apps
defaults write -g NSAppSleepDisabled -bool true

# Disable automatic termination of inactive apps
defaults write -g NSDisableAutomaticTermination -bool true

# Show fast user switching menu as: Icon
defaults write -g userMenuExtraStyle -int 2

# Prefer tabs when CMD-n
# https://thegreatescapism.com/tab-preferences-in-macos/
defaults write -g AppleWindowTabbingMode -string "always"

#
# Audio and sound effects
#
echo "Setting Sound preferences"

# Enable feedback when changing volume
defaults write -g com.apple.sound.beep.feedback -bool true

# Disable flashing the screen when an alert sound occurs (accessibility)
defaults write -g com.apple.sound.beep.flash -bool false

# Alert volume 50%
defaults write -g com.apple.sound.beep.volume -float 0.6065307

# Disable interface sound effects
defaults write -g com.apple.sound.uiaudio.enabled -bool false

#
# Desktop & Screen Saver
#
echo "Setting Desktop & Screen Saver preferences"

# No translucent menu bar
# defaults write -g "AppleEnableMenuBarTransparency" -bool false

# Ask for password after 5 seconds
defaults write com.apple.screensaver askForPassword -int 1
defaults write com.apple.screensaver askForPasswordDelay -int 5

# Hot corners -> bottom left -> start screen saver
defaults write com.apple.dock "wvous-bl-corner" -int 5
defaults write com.apple.dock "wvous-bl-modifier" -int 0

###############################################################################
# Screen capture                                                              #
###############################################################################

# Save screenshots to the desktop
defaults write com.apple.screencapture location -string "${HOME}/Downloads/ScreenShots"

# Save screenshots in PNG format (other options: BMP, GIF, JPG, PDF, TIFF)
defaults write com.apple.screencapture type -string "png"

# Disable shadow in screenshots
defaults write com.apple.screencapture disable-shadow -bool true

#
# Mouse and trackpad
#
echo "Setting Mouse and Trackpad preferences"

# Enable tap to click
defaults write com.apple.AppleMultitouchTrackpad Clicking -bool true

# Disable natural scroll direction
defaults write -g com.apple.swipescrolldirection -bool false

# Swipe between pages with two fingers
defaults write -g AppleEnableSwipeNavigateWithScrolls -bool true

# Enable secondary click with two fingers
defaults write com.apple.AppleMultitouchTrackpad TrackpadRightClick -bool true

# Disable secondary click in bottom right or left corner if secondary click with two fingers is enabled
defaults write com.apple.AppleMultitouchTrackpad TrackpadCornerSecondaryClick -int 0

#
# Accessibility
#

# Reduce motion
defaults write com.apple.universalaccess reduceMotion -bool true

# Reduce transparency
# defaults write com.apple.universalaccess reduceTransparency -bool true

# Show window title icons
defaults write com.apple.universalaccess showWindowTitlebarIcons -bool true

# Show toolbar button shapes
defaults write com.apple.universalaccess showToolbarButtonShapes -bool true

# =====================
# Applications
# =====================

#
# Archive Utility
#
echo "Setting Archive Utility preferences"

# Move archives to trash after extraction
defaults write com.apple.archiveutility "dearchive-into" -string "."

# Move archives to trash after extraction
defaults write com.apple.archiveutility "dearchive-move-after" -string "~/.Trash"

# Move archives to trash after extraction
defaults write com.apple.archiveutility "dearchive-recursively" -bool true

# Don't reveal extracted items
defaults write com.apple.archiveutility "dearchive-reveal-after" -bool false

#
# Finder
#
echo "Setting Finder preferences"

# Expand the "Open with" and "Sharing & Permissions" panes
defaults write com.apple.finder FXInfoPanesExpanded -dict OpenWith -bool true Privileges -bool true

# Show status bar
defaults write com.apple.finder ShowStatusBar -bool true

# New window points to home
defaults write com.apple.finder NewWindowTarget -string "PfHm"

# Finder: disable window animations and Get Info animations
defaults write com.apple.finder DisableAllAnimations -bool true

# Show icons for hard drives, servers, and removable media on the desktop
defaults write com.apple.finder ShowExternalHardDrivesOnDesktop -bool true
defaults write com.apple.finder ShowHardDrivesOnDesktop -bool true
defaults write com.apple.finder ShowMountedServersOnDesktop -bool true
defaults write com.apple.finder ShowRemovableMediaOnDesktop -bool true

# Finder: show all filename extensions
defaults write -g AppleShowAllExtensions -bool true

# Finder: allow text selection in Quick Look
defaults write com.apple.finder QLEnableTextSelection -bool true

# When performing a search, search the current folder by default
defaults write com.apple.finder FXDefaultSearchScope -string "SCcf"

# Avoid creating .DS_Store files on network volumes
defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true

# Use column view
defaults write com.apple.finder FXPreferredViewStyle -string "clmv"

# No windows, just new tabs
defaults write com.apple.finder FinderSpawnTab -bool true

#
# Desktop & Dock
#
echo "Setting Desktop & Dock preferences"

# Position (left, bottom, right)
defaults write com.apple.dock orientation -string "bottom"

# Hide recent apps
defaults write com.apple.dock show-recents -bool false

# Disable click wallpaper to show desktop items
defaults write com.apple.WindowManager EnableStandardClickToShowDesktop -bool false

# Disable Stage Manager
defaults write com.apple.WindowManager GloballyEnabled -bool false

# Show desktop icons
defaults write com.apple.WindowManager StandardHideDesktopIcons -bool false

# Show widgets
defaults write com.apple.WindowManager StandardHideWidgets -bool false

#
# Safari & WebKit
#
echo "Setting Safari & WebKit preferences"

# Appearance

# Show status bar
defaults write com.apple.Safari ShowStatusBar -bool true

# Show favorites bar
defaults write com.apple.Safari "ShowFavoritesBar-v2" -bool true

# Don't show tab bar
defaults write com.apple.Safari AlwaysShowTabBar -bool false

# No background colors in toolbar
defaults write com.apple.Safari NeverUseBackgroundColorInToolbar -bool true

# General settings

# Safari opens with: A new window
defaults write com.apple.Safari AlwaysRestoreSessionAtLaunch -bool false

# New windows open with: Empty Page
defaults write com.apple.Safari NewWindowBehavior -int 1

# New tabs open with: Empty Page
defaults write com.apple.Safari NewTabBehavior -int 1

# Homepage
defaults write com.apple.Safari HomePage -string "about:blank"

# Don't open "safe" files after downloading
defaults write com.apple.Safari AutoOpenSafeDownloads -bool false

# Tabs settings

# Open pages in tabs instead of windows: automatically
defaults write com.apple.Safari TabCreationPolicy -int 1

# Don't make new tabs active
defaults write com.apple.Safari OpenNewTabsInFront -bool false

# Command-clicking a link creates tabs
defaults write com.apple.Safari CommandClickMakesTabs -bool true

# Autofill settings

# Don't autofill anything
defaults write com.apple.Safari AutoFillCreditCardData -bool false
defaults write com.apple.Safari AutoFillFromAddressBook -bool false
defaults write com.apple.Safari AutoFillMiscellaneousForms -bool false
defaults write com.apple.Safari AutoFillPasswords -bool false

# Search settings

# Search engine: Google
defaults write -g NSPreferredWebServices -dict 'NSWebServicesProviderWebSearch' '{ NSDefaultDisplayName = Google; NSProviderIdentifier = com.google.www; }'
defaults write com.apple.Safari SearchProviderShortName -string "Google"

# Search engine: Bing
# defaults write -g NSPreferredWebServices -dict 'NSWebServicesProviderWebSearch' '{ NSDefaultDisplayName = Bing; NSProviderIdentifier = com.bing.www; }'
# defaults write com.apple.Safari SearchProviderShortName -string "Bing"

# Search engine: DuckDuckGo
# defaults write -g NSPreferredWebServices -dict 'NSWebServicesProviderWebSearch' '{ NSDefaultDisplayName = DuckDuckGo; NSProviderIdentifier = com.duckduckgo; }'
# defaults write com.apple.Safari SearchProviderShortName -string "DuckDuckGo"

# Enable search engine suggestions
defaults write com.apple.Safari SuppressSearchSuggestions -bool false

# Smart search field:

# Disable Safari suggestions
defaults write com.apple.Safari UniversalSearchEnabled -bool false
defaults write com.apple.Safari UniversalSearchFeatureNotificationHasBeenDisplayed -bool true

# Disable top hit preloading
defaults write com.apple.Safari PreloadTopHit -bool false

# Disable quick website search
defaults write com.apple.Safari WebsiteSpecificSearchEnabled -bool false

# Security settings

# Warn About Fraudulent Websites
defaults write com.apple.Safari WarnAboutFraudulentWebsites -bool true

# Enable plug-ins
defaults write com.apple.Safari WebKitPluginsEnabled -bool true
defaults write com.apple.Safari com.apple.Safari.ContentPageGroupIdentifier.WebKit2PluginsEnabled -bool true

# Enable Java
defaults write com.apple.Safari WebKitJavaEnabled -bool true
defaults write com.apple.Safari com.apple.Safari.ContentPageGroupIdentifier.WebKit2JavaEnabled -bool true

# Enable JavaScript
defaults write com.apple.Safari WebKitJavaScriptEnabled -bool true
defaults write com.apple.Safari com.apple.Safari.ContentPageGroupIdentifier.WebKit2JavaScriptEnabled -bool true

# Block pop-up windows
defaults write com.apple.Safari WebKitJavaScriptCanOpenWindowsAutomatically -bool false
defaults write com.apple.Safari com.apple.Safari.ContentPageGroupIdentifier.WebKit2JavaScriptCanOpenWindowsAutomatically -bool false

# Reading list
defaults write com.apple.Safari com.apple.Safari.ReadingListFetcher.WebKit2PluginsEnabled -bool false
defaults write com.apple.Safari com.apple.Safari.ReadingListFetcher.WebKit2LoadsImagesAutomatically -bool false
defaults write com.apple.Safari com.apple.Safari.ReadingListFetcher.WebKit2LoadsSiteIconsIgnoringImageLoadingPreference -bool true
defaults write com.apple.Safari com.apple.Safari.ReadingListFetcher.WebKit2JavaScriptEnabled -bool false

# Privacy settings

# Cookies and website data
# - Always block
#defaults write com.apple.Safari WebKitStorageBlockingPolicy -int 2
#defaults write com.apple.Safari com.apple.Safari.ContentPageGroupIdentifier.WebKit2StorageBlockingPolicy -int 2

# Website use of location services
# 0 = Deny without prompting
# 1 = Prompt for each website once each day
# 2 = Prompt for each website one time only
defaults write com.apple.Safari SafariGeolocationPermissionPolicy -int 2

# Do not track
defaults write com.apple.Safari SendDoNotTrackHTTPHeader -bool true

# Notifications

# Don't even ask about the push notifications
defaults write com.apple.Safari CanPromptForPushNotifications -bool false

# Extensions settings

# Update extensions automatically
defaults write com.apple.Safari InstallExtensionUpdatesAutomatically -bool true

# Advanced settings

# Disable Safari’s thumbnail cache for History and Top Sites
defaults write com.apple.Safari DebugSnapshotsUpdatePolicy -int 2

# Make Safari’s search banners default to Contains instead of Starts With
defaults write com.apple.Safari FindOnPageMatchesWordStartsOnly -bool false

# Enable the Develop menu and the Web Inspector in Safari
defaults write com.apple.Safari IncludeInternalDebugMenu -bool true
defaults write com.apple.Safari WebKitDeveloperExtrasEnabledPreferenceKey -bool true
defaults write com.apple.Safari com.apple.Safari.ContentPageGroupIdentifier.WebKit2DeveloperExtrasEnabled -bool true

# Add a context menu item for showing the Web Inspector in web views
defaults write -g WebKitDeveloperExtras -bool true

#
# Disk Utility
#
echo "Setting Disk Utility preferences"

# Enable the debug menu in Disk Utility
defaults write com.apple.DiskUtility DUDebugMenuEnabled -bool true
defaults write com.apple.DiskUtility advanced-image-options -bool true

# View -> Show All Devices
defaults write com.apple.DiskUtility SidebarShowAllDevices -bool true

# Show APFS snapshots
defaults write com.apple.DiskUtility WorkspaceShowAPFSSnapshots -bool true

#
# Terminal
#
echo "Setting Terminal preferences"

# ----------------------------------------------
# Create a new "Basic Improved" profile
# ----------------------------------------------
defaults write com.apple.Terminal "Window Settings" -dict-add "Basic Improved" "
<dict>
    <key>Font</key>
    <data>
    YnBsaXN0MDDUAQIDBAUGGBlYJHZlcnNpb25YJG9iamVjdHNZJGFy
    Y2hpdmVyVCR0b3ASAAGGoKQHCBESVSRudWxs1AkKCwwNDg8QVk5T
    U2l6ZVhOU2ZGbGFnc1ZOU05hbWVWJGNsYXNzI0AmAAAAAAAAEBCA
    AoADXlNGTW9uby1SZWd1bGFy0hMUFRZaJGNsYXNzbmFtZVgkY2xh
    c3Nlc1ZOU0ZvbnSiFRdYTlNPYmplY3RfEA9OU0tleWVkQXJjaGl2
    ZXLRGhtUcm9vdIABCBEaIy0yNzxCS1JbYmlydHZ4h4yXoKeqs8XI
    zQAAAAAAAAEBAAAAAAAAABwAAAAAAAAAAAAAAAAAAADP
    </data>
    <key>FontAntialias</key>
    <true/>
    <key>FontWidthSpacing</key>
    <real>1.004032258064516</real>
    <key>ProfileCurrentVersion</key>
    <real>2.0499999999999998</real>
    <key>columnCount</key>
    <integer>100</integer>
    <key>name</key>
    <string>Basic Improved</string>
    <key>rowCount</key>
    <integer>45</integer>
    <key>shellExitAction</key>
    <integer>1</integer>
    <key>type</key>
    <string>Window Settings</string>
</dict>
"

# Shell opens with: /bin/bash
# defaults write com.apple.Terminal Shell -string "/bin/bash"

# Set the "Basic Improved" as the default
defaults write com.apple.Terminal "Startup Window Settings" -string "Basic Improved"
defaults write com.apple.Terminal "Default Window Settings" -string "Basic Improved"

# ==============================================
# Kill affected applications
# ==============================================

function killallApps() {
	killall "Finder" >/dev/null 2>&1
	killall "SystemUIServer" >/dev/null 2>&1
	killall "Dock" >/dev/null 2>&1

	appsToKill=(
		"Activity Monitor"
		"Calendar"
		"Disk Utility"
		"Safari"
		"System Preferences"
	)

	for app in "${appsToKill[@]}"; do
		killall "${app}" >/dev/null 2>&1
		if [[ $? -eq 0 ]]; then
			# We just killed an app so restart it
			open -a "${app}"
		fi
	done

	echo "Note that some of these changes require a logout/restart to take effect."
}

printf "Restart the affected applications? (y/n): "
read killallReply
if [[ $killallReply =~ ^[Yy]$ ]]; then
	killallApps
fi

exit 0
