#!/usr/bin/env bash
# Description: Search GitHub topics

set -euo pipefail

if [ $# -eq 0 ]; then
  echo "Usage: search_gh_topic <search_query> [topic]"
  exit 1
fi

SEARCH_QUERY="$1"
TOPIC="${2:-gh-extension}"

echo "Searching GitHub for '$SEARCH_QUERY' with topic '$TOPIC'..."

gh search repos "$SEARCH_QUERY" --topic "$TOPIC" --limit 50 |
  fzf --preview 'gh repo view {1}' |
  awk '{print $1}' |
  xargs -I_ open "https://github.com/_"
