#!/usr/bin/env bash
# Description: Prepare files for language models

set -euo pipefail

exclude_args=()
search_path="."

# Parse arguments
while [[ $# -gt 0 ]]; do
  case $1 in
  -E | --exclude)
    exclude_args+=("--exclude" "$2")
    shift 2
    ;;
  *)
    search_path="$1"
    shift
    ;;
  esac
done

fd -t f -0 "${exclude_args[@]}" . "$search_path" |
  while IFS= read -r -d '' file; do
    if file --mime-type "$file" | grep -q text/; then
      echo
      echo "# File: ===== $file ====="
      echo
      cat "$file"
      echo
    fi
  done | pbcopy
