#!/usr/bin/env bash
# Description: Make video iPad-ready

set -euo pipefail

if [ $# -ne 2 ]; then
  echo "Usage: vid_ipad <input> <output>"
  exit 1
fi

ffmpeg -i "$1" -af "
    loudnorm=I=-14:TP=-1.5:LRA=7,
    acompressor=threshold=-20dB:ratio=4:attack=200:release=1000,
    equalizer=f=30:t=q:w=1:g=5
" -c:v libx264 -crf 17 -preset slow -c:a aac -b:a 192k "$2"
