# TPM plugins
set -g @plugin '27medkamal/tmux-session-wizard'
set -g @plugin 'kapral18/tmux-theme-catppuccin'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-pain-control'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-sessionist'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'wfxr/tmux-fzf-url'

# Catpuccin
set -g @catppuccin_flavor 'frappe'

# Continuum
set -g @continuum-restore 'on'
set -g @continuum-save-interval '1'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/plugins/tpm/tpm'

# tpm overrides

# Override tmux-pain-control because >< don't work
unbind-key >
unbind-key <
unbind-key C-h
unbind-key C-l

# Pass through C-S-<hjkl> so that we can use them in neovim
# \033 (octal) or \x1b (hex) is the escape character
# \x1b[ is the CSI (Control Sequence Introducer)
bind-key -n C-S-h send-keys "\033[104;6u"
bind-key -n C-S-j send-keys "\033[106;6u"
bind-key -n C-S-k send-keys "\033[107;6u"
bind-key -n C-S-l send-keys "\033[108;6u"

bind-key s switch-client -T k18
# <prefix>sh to swap left
bind-key -T k18 h swap-pane -d -t -1
# <prefix>sl to swap right
bind-key -T k18 l swap-pane -d -t +1
set -g default-terminal "tmux-256color"
set -as terminal-features ',tmux*:clipboard'
set -as terminal-features ',xterm*:clipboard'
set -as terminal-overrides ',tmux*:Tc'
set -as terminal-overrides ',xterm*:Tc'
set -gq allow-passthrough on
set -g visual-activity off
set -g renumber-windows on
set -g history-limit 50000
# Update files on focus (using for vim)
set -g focus-events on
set -g status-keys emacs
set -g display-time 2000
set -g status-interval 5
set -gs escape-time 0
set -g -s set-clipboard on
set -g mouse on

# set vi-mode
set-window-option -g mode-keys vi

unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# No confirm to kill
bind-key & kill-window
bind-key x kill-pane

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Shift F to toggle max-pane
unbind-key z 
unbind-key f
bind-key f resize-pane -Z

# Reload config
bind r source-file ~/.config/tmux/tmux.conf

# History and renaming
set -g history-limit 10000
set -g allow-rename off

# keybindings
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# lowfi
# [p]lay/[p]ause
bind-key -n F12 run-shell 'tmux-lowfi p'
# [s]kip
bind-key -n F11 run-shell 'tmux-lowfi s'
