complete -c ,check-backport-progress -l merged-label -r -d 'Label identifying merged PRs needing backport' -a '(gh label list --limit 200 --json name --jq ".[].name" 2>/dev/null)'
complete -c ,check-backport-progress -l required-labels -r -d 'Space-separated required labels for open PRs' -a '(gh label list --limit 200 --json name --jq ".[].name" 2>/dev/null)'
complete -c ,check-backport-progress -l branches -r -d 'Space-separated target branches to check' -a '(git for-each-ref --format="%(refname:strip=2)" refs/heads refs/remotes 2>/dev/null)'
complete -c ,check-backport-progress -l upstream -r -d 'Name of the upstream git remote' -a '(git remote 2>/dev/null)'
complete -c ,check-backport-progress -s h -l help -d 'Show help'
