complete -c ',copilot-codex' -w ',copilot'
complete -c ',copilot-codex' -s m -l model -x -a '(__comma_provider_models codex)' -d 'Override Codex backend model'
complete -c ',copilot-codex' -l effort -x -a 'none minimal low medium high xhigh max ultra' -d 'Override Codex reasoning effort'
complete -c ',copilot-codex' -l reasoning-effort -x -a 'none minimal low medium high xhigh max ultra' -d 'Override Codex reasoning effort'
complete -c ',copilot-codex' -s h -l help -d 'Show Codex subscription wrapper help'
