complete -c ',copilot-openrouter' -f
complete -c ',copilot-openrouter' -n 'not __fish_seen_argument -s m -l model' -x -a '(__comma_provider_models openrouter)' -d 'Use OpenRouter model'
complete -c ',copilot-openrouter' -l model -s m -x -a '(__comma_provider_models openrouter)' -d 'Override OpenRouter model'
complete -c ',copilot-openrouter' -l prompt -s p -r -d 'Execute a prompt in non-interactive mode'
complete -c ',copilot-openrouter' -l interactive -s i -r -d 'Start interactive mode and execute prompt'
complete -c ',copilot-openrouter' -l agent -x -d 'Use a custom Copilot agent'
complete -c ',copilot-openrouter' -l allow-all -d 'Enable all permissions'
complete -c ',copilot-openrouter' -l yolo -d 'Enable all permissions'
complete -c ',copilot-openrouter' -l context -x -a 'default long_context' -d 'Set context tier'
complete -c ',copilot-openrouter' -l effort -x -a 'none low medium high xhigh max' -d 'Set reasoning effort'
complete -c ',copilot-openrouter' -l reasoning-effort -x -a 'none low medium high xhigh max' -d 'Set reasoning effort'
complete -c ',copilot-openrouter' -l thinking -x -a 'none low medium high xhigh max' -d 'Set reasoning effort'
complete -c ',copilot-openrouter' -l no-thinking -d 'Disable reasoning effort'
complete -c ',copilot-openrouter' -l help -s h -d 'Show Copilot help'
