complete -c ',copilot-litellm' -f
complete -c ',copilot-litellm' -n 'not __fish_seen_argument -s m -l model' -x -a '(__comma_provider_models litellm)' -d 'Use LiteLLM gateway model'
complete -c ',copilot-litellm' -l model -s m -x -a '(__comma_provider_models litellm)' -d 'Override LiteLLM gateway model'
complete -c ',copilot-litellm' -l prompt -s p -r -d 'Execute a prompt in non-interactive mode'
complete -c ',copilot-litellm' -l interactive -s i -r -d 'Start interactive mode and execute prompt'
complete -c ',copilot-litellm' -l agent -x -d 'Use a custom Copilot agent'
complete -c ',copilot-litellm' -l allow-all -d 'Enable all permissions'
complete -c ',copilot-litellm' -l yolo -d 'Enable all permissions'
complete -c ',copilot-litellm' -l context -x -a 'default long_context' -d 'Set context tier'
complete -c ',copilot-litellm' -l effort -x -a 'none low medium high xhigh max' -d 'Set reasoning effort'
complete -c ',copilot-litellm' -l reasoning-effort -x -a 'none low medium high xhigh max' -d 'Set reasoning effort'
complete -c ',copilot-litellm' -l thinking -x -a 'none low medium high xhigh max' -d 'Set reasoning effort'
complete -c ',copilot-litellm' -l no-thinking -d 'Disable reasoning effort'
complete -c ',copilot-litellm' -l help -s h -d 'Show Copilot help'
