complete -c ',jest-test-title-report' -l before -r -a '(__fish_complete_directories)' -d 'Before worktree path'
complete -c ',jest-test-title-report' -l after -r -a '(__fish_complete_directories)' -d 'After worktree path'
complete -c ',jest-test-title-report' -l scope -r -d 'Relative scope path'
complete -c ',jest-test-title-report' -l out -r -d 'Output CSV path'
complete -c ',jest-test-title-report' -l replacements -r -a '(__fish_complete_suffix .json)' -d 'Consolidation map JSON'
complete -c ',jest-test-title-report' -l gist -d 'Upload CSV to gist'
complete -c ',jest-test-title-report' -l gist-new -d 'Create a new gist'
complete -c ',jest-test-title-report' -l gist-state -r -a '(__fish_complete_suffix .json)' -d 'Gist state path'
complete -c ',jest-test-title-report' -l gist-filename -r -d 'Gist filename'
complete -c ',jest-test-title-report' -l gist-public -d 'Create public gist'
complete -c ',jest-test-title-report' -l gist-desc -r -d 'Gist description'
complete -c ',jest-test-title-report' -s h -l help -d 'Show help'
