prSections:
  - title: Elastic PRs Open
    filters: is:open author:@me org:elastic
    layout:
      author:
        hidden: true
  - title: Elastic PRs Involved
    filters: is:open commenter:@me -author:@me org:elastic
  - title: Personal PRs Open
    filters: is:open -author:@me -org:elastic
    layout:
      author:
        hidden: true
  - title: Personal PRs Involved
    filters: is:open commented:@me -author:@me -org:elastic
issuesSections:
  - title: Elastic Issues Open
    filters: is:open author:@me org:elastic
    layout:
      author:
        hidden: true
  - title: Elastic Issues Assigned
    filters: is:open assignee:@me org:elastic
  - title: Elastic Issues Involved
    filters: is:open commenter:@me -author:@me org:elastic
  - title: Personal Issues Open
    filters: is:open -author:@me -org:elastic
    layout:
      author:
        hidden: true
  - title: Personal Issues Assigned
    filters: is:open assignee:@me -org:elastic
  - title: Personal Issues Involved
    filters: is:open commenter:@me -author:@me -org:elastic
defaults:
  preview:
    open: true
    width: 50
  prsLimit: 20
  issuesLimit: 20
  view: prs
  layout:
    prs:
      updatedAt:
        width: 7
      repo:
        width: 15
      author:
        width: 15
      assignees:
        width: 20
        hidden: true
      base:
        width: 15
        hidden: true
      lines:
        width: 16
    issues:
      updatedAt:
        width: 7
      repo:
        width: 15
      creator:
        width: 10
      assignees:
        width: 20
        hidden: true
  refetchIntervalMinutes: 30
keybindings:
  issues:
    - key: 8
      command: >
        tmux display-popup -d {{.RepoPath}} -w 80% -h 90% -E 'nvim -c ":Octo issue edit {{.IssueNumber}}"'
    - key: 9
      command: >
        tmux display-popup -d {{.RepoPath}} -w 80% -h 90% -E 'nvim -c ":Octo issue create"'
  prs:
    - key: O
      command: >
        tmux new-window -c {{.RepoPath}} 'nvim -c ":Octo pr edit {{.PrNumber}}"'
repoPaths: {}
theme:
  ui:
    table:
      showSeparator: true
pager:
  diff: ""
confirmQuit: false
