# Theme 
include ./themes/mocha.conf

# Font
include ./symbols-map.conf

# =========================================================
# Settings
enabled_layouts                 tall, stack, horizontal
update_check_interval           0
enable_audio_bell               no
allow_remote_control            yes
strip_trailing_spaces           smart
mouse_hide_wait                 3.0
open_url_with                   default
copy_on_select                  yes
sync_to_monitor                 yes
inactive_text_alpha             0.9
linux_display_server            auto
cursor_shape                    block
url_style                       dotted
disable_ligatures               never
macos_option_as_alt             yes
confirm_os_window_close         0
detect_urls                     1
term                            xterm-kitty
repaint_delay                   5
input_delay                     1
background_opacity              0.95
shell                           /opt/homebrew/bin/fish
font_family                     JetBrainsMono Nerd Font Mono
font_size                       14.0
scrollback_lines                10000


# UI
tab_bar_style powerline
tab_powerline_style slanted
tab_title_template "{index}:{tab.active_process_name}"

# =========================================================
# Maps
kitty_mod ctrl+shift

# Some useful default keymaps I always forget:
# Insert selected path
map ctrl+shift+p>f kitten hints --type path --program -
# Insert selected line
map ctrl+shift+p>l kitten hints --type line --program -
# Insert selected word
map ctrl+shift+p>w kitten hints --type word --program -
# Insert selected hash
map ctrl+shift+p>h kitten hints --type hash --program -
# Insert selected url
map ctrl+shift+p>u kitten hints --type url --program -
# Reload config
map ctrl+shift+f5 load_config_file

# layouts
map ctrl+shift+z toggle_layout stack

# =========================================================

map ctrl+shift+enter new_window_with_cwd
map ctrl+shift+t new_tab_with_cwd

# debugging
map ctrl+shift+d launch --keep-focus --cwd=current kitty --debug-font-fallback
