return {
  "johmsalas/text-case.nvim",
  lazy = false,
  keys = {
    {
      "<leader>ccau",
      ":lua require('textcase').current_word('to_upper_case')<CR>",
      desc = "current_word('to_upper_case')<CR>",
      mode = { "x", "n", "o" },
    },
    {
      "<leader>ccal",
      ":lua require('textcase').current_word('to_lower_case')<CR>",
      desc = "current_word('to_lower_case')<CR>",
      mode = { "x", "n", "o" },
    },
    {
      "<leader>ccas",
      ":lua require('textcase').current_word('to_snake_case')<CR>",
      desc = "current_word('to_snake_case')<CR>",
      mode = { "x", "n", "o" },
    },
    {
      "<leader>ccad",
      ":lua require('textcase').current_word('to_dash_case')<CR>",
      desc = "current_word('to_dash_case')<CR>",
      mode = { "x", "n", "o" },
    },
    {
      "<leader>ccan",
      ":lua require('textcase').current_word('to_constant_case')<CR>",
      desc = "current_word('to_constant_case')<CR>",
      mode = { "x", "n", "o" },
    },
    {
      "<leader>ccad",
      ":lua require('textcase').current_word('to_dot_case')<CR>",
      desc = "current_word('to_dot_case')<CR>",
      mode = { "x", "n", "o" },
    },
    {
      "<leader>ccaa",
      ":lua require('textcase').current_word('to_phrase_case')<CR>",
      desc = "current_word('to_phrase_case')<CR>",
      mode = { "x", "n", "o" },
    },
    {
      "<leader>ccac",
      ":lua require('textcase').current_word('to_camel_case')<CR>",
      desc = "current_word('to_camel_case')<CR>",
      mode = { "x", "n", "o" },
    },
    {
      "<leader>ccap",
      ":lua require('textcase').current_word('to_pascal_case')<CR>",
      desc = "current_word('to_pascal_case')<CR>",
      mode = { "x", "n", "o" },
    },
    {
      "<leader>ccat",
      ":lua require('textcase').current_word('to_title_case')<CR>",
      desc = "current_word('to_title_case')<CR>",
      mode = { "x", "n", "o" },
    },
    {
      "<leader>ccaf",
      ":lua require('textcase').current_word('to_path_case')<CR>",
      desc = "current_word('to_path_case')<CR>",
      mode = { "x", "n", "o" },
    },

    {
      "<leader>ccaU",
      ":lua require('textcase').lsp_rename('to_upper_case')<CR>",
      desc = "lsp_rename('to_upper_case')<CR>",
      mode = { "x", "n", "o" },
    },
    {
      "<leader>ccaL",
      ":lua require('textcase').lsp_rename('to_lower_case')<CR>",
      desc = "lsp_rename('to_lower_case')<CR>",
      mode = { "x", "n", "o" },
    },
    {
      "<leader>ccaS",
      ":lua require('textcase').lsp_rename('to_snake_case')<CR>",
      desc = "lsp_rename('to_snake_case')<CR>",
      mode = { "x", "n", "o" },
    },
    {
      "<leader>ccaD",
      ":lua require('textcase').lsp_rename('to_dash_case')<CR>",
      desc = "lsp_rename('to_dash_case')<CR>",
      mode = { "x", "n", "o" },
    },
    {
      "<leader>ccaN",
      ":lua require('textcase').lsp_rename('to_constant_case')<CR>",
      desc = "lsp_rename('to_constant_case')<CR>",
      mode = { "x", "n", "o" },
    },
    {
      "<leader>ccaD",
      ":lua require('textcase').lsp_rename('to_dot_case')<CR>",
      desc = "lsp_rename('to_dot_case')<CR>",
      mode = { "x", "n", "o" },
    },
    {
      "<leader>ccaA",
      ":lua require('textcase').lsp_rename('to_phrase_case')<CR>",
      desc = "lsp_rename('to_phrase_case')<CR>",
      mode = { "x", "n", "o" },
    },
    {
      "<leader>ccaC",
      ":lua require('textcase').lsp_rename('to_camel_case')<CR>",
      desc = "lsp_rename('to_camel_case')<CR>",
      mode = { "x", "n", "o" },
    },
    {
      "<leader>ccaP",
      ":lua require('textcase').lsp_rename('to_pascal_case')<CR>",
      desc = "lsp_rename('to_pascal_case')<CR>",
      mode = { "x", "n", "o" },
    },
    {
      "<leader>ccaT",
      ":lua require('textcase').lsp_rename('to_title_case')<CR>",
      desc = "lsp_rename('to_title_case')<CR>",
      mode = { "x", "n", "o" },
    },
    {
      "<leader>ccaF",
      ":lua require('textcase').lsp_rename('to_path_case')<CR>",
      desc = "lsp_rename('to_path_case')<CR>",
      mode = { "x", "n", "o" },
    },

    {
      "<leader>cceu",
      ":lua require('textcase').operator('to_upper_case')<CR>",
      desc = "operator('to_upper_case')<CR>",
      mode = { "x", "n", "o" },
    },
    {
      "<leader>ccel",
      ":lua require('textcase').operator('to_lower_case')<CR>",
      desc = "operator('to_lower_case')<CR>",
      mode = { "x", "n", "o" },
    },
    {
      "<leader>cces",
      ":lua require('textcase').operator('to_snake_case')<CR>",
      desc = "operator('to_snake_case')<CR>",
      mode = { "x", "n", "o" },
    },
    {
      "<leader>cced",
      ":lua require('textcase').operator('to_dash_case')<CR>",
      desc = "operator('to_dash_case')<CR>",
      mode = { "x", "n", "o" },
    },
    {
      "<leader>ccen",
      ":lua require('textcase').operator('to_constant_case')<CR>",
      desc = "operator('to_constant_case')<CR>",
      mode = { "x", "n", "o" },
    },
    {
      "<leader>cced",
      ":lua require('textcase').operator('to_dot_case')<CR>",
      desc = "operator('to_dot_case')<CR>",
      mode = { "x", "n", "o" },
    },
    {
      "<leader>ccea",
      ":lua require('textcase').operator('to_phrase_case')<CR>",
      desc = "operator('to_phrase_case')<CR>",
      mode = { "x", "n", "o" },
    },
    {
      "<leader>ccec",
      ":lua require('textcase').operator('to_camel_case')<CR>",
      desc = "operator('to_camel_case')<CR>",
      mode = { "x", "n", "o" },
    },
    {
      "<leader>ccep",
      ":lua require('textcase').operator('to_pascal_case')<CR>",
      desc = "operator('to_pascal_case')<CR>",
      mode = { "x", "n", "o" },
    },
    {
      "<leader>ccet",
      ":lua require('textcase').operator('to_title_case')<CR>",
      desc = "operator('to_title_case')<CR>",
      mode = { "x", "n", "o" },
    },
    {
      "<leader>ccef",
      ":lua require('textcase').operator('to_path_case')<CR>",
      desc = "operator('to_path_case')<CR>",
      mode = { "x", "n", "o" },
    },
  },
  opts = {
    default_keymappings_enabled = false,
  },
}
