[bell]
animation = "EaseOutExpo"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true
transparent_background_colors = true

[[colors.indexed_colors]]
color = "0xF8BD96"
index = 16

[[colors.indexed_colors]]
color = "0xF5E0DC"
index = 17

[colors.bright]
black = "0x988BA2"
blue = "0x96CDFB"
cyan = "0x89DCEB"
green = "0xABE9B3"
magenta = "0xF5C2E7"
red = "0xF28FAD"
white = "0xD9E0EE"
yellow = "0xFAE3B0"

[colors.cursor]
cursor = "0xF5E0DC"
text = "0x1E1D2F"

[colors.normal]
black = "0x6E6C7E"
blue = "0x96CDFB"
cyan = "0x89DCEB"
green = "0xABE9B3"
magenta = "0xF5C2E7"
red = "0xF28FAD"
white = "0xD9E0EE"
yellow = "0xFAE3B0"

[colors.primary]
background = "0x1E1D2F"
foreground = "0xD9E0EE"

[env]
TERM = "alacritty-direct"

[font]
size = 12

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "JetBrainsMono Nerd Font"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[mouse]
hide_when_typing = true

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[scrolling]
history = 10000
multiplier = 4

[shell]
program = "/opt/homebrew/bin/fish"

[window]
decorations = "transparent"
dynamic_title = true
option_as_alt = "OnlyLeft"
startup_mode = "Maximized"
position = "None"
dynamic_padding = true
opacity = 0.95
blur = true
decorations_theme_variant = "None"
resize_increments = true

[window.padding]
x = 4
y = 4

[cursor]
unfocused_hollow = false
thickness = 0.15

[terminal]
osc52 = "CopyPaste"
