import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

// Auto-generate the sidebar from the filesystem layout under `../docs`.
// Folders → categories. Add `_category_.json` next to a folder if you need
// to override its label or position.
const sidebars: SidebarsConfig = {
  docs: [ { type: 'autogenerated', dirName: '.' } ],
}

export default sidebars
